version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/chave10-novo/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/chave10-novo/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
